
title: Nicole Kim Creates
email: nicolekimcreates@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I will write about my art works and theory of design here.
baseurl: # the subpath of your site, e.g. /blog
url: "https://nicolekimcreates.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ""
github_username:  "nicolekimcreates"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
